"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCodes = void 0;
exports.ErrorCodes = {
    BAD_REQUEST: 'BAD_REQUEST',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    RATE_LIMITED: 'RATE_LIMITED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    // Tenant & Auth specific
    TENANT_MISMATCH: 'TENANT_MISMATCH',
    ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    // Incident specific
    INCIDENT_NOT_FOUND: 'INCIDENT_NOT_FOUND',
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
    SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
    TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
    // SLA & AI
    SLA_POLICY_NOT_FOUND: 'SLA_POLICY_NOT_FOUND',
    AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
};
//# sourceMappingURL=errors.js.map